### ISSUE TITLE
Unable to connect to server - The server is unavailable

### ISSUE THREAD

**Issue by reado** [ptrofimov/beanstalk_console#100]
I'm having troubles trying to connect my local homestead instance (which is Laravel's Vagrant environment) and I'm unable to connect the Beanstalkd Console to my server instance.

I also followed Jeffery Way's tutorial like [issue 58] (https://github.com/ptrofimov/beanstalk_console/issues/58) and was unable to get either any errors to show up using error_reporting(0) or any connection to my Homestead server.

I also see the php warning when I click on 'All Tubes'
```
Notice: Undefined variable: tubes in [...]/beanstalk_console/lib/tpl/main.php on line 90
```

It appears that the previous ticket has been closed, but I'm still experiencing troubles.

I did a fresh install using composer of the Beanstalkd Console (version 1.7) and got it serving pages using 
```
vagrant up
```

Any idea why I might be having troubles?

Thanks

**Comment by pentium10** [comment]
error_reporting(0) actually means turn off error reporting.

**Comment by pentium10** [comment]
find me with my username on gmail for a chat

**Comment by ormrepo** [comment]
I had the same issue and it remains unresolved good luck !!!

**Comment by pentium10** [comment]
get in touch with me, I just got one sorted out, it had a wrong PHP installation

**Comment by pentium10** [comment]
so @reado  and @ormrepo I didn't get any request to you, I am here to help you.

**Comment by ormrepo** [comment]
Hi there
Sorry for the late reply, Its been a number of months since I raised the issue and I had decided to ditch the server I had prepared and I am now using Laravel Homestead as my server.
This has beanstalk integrated in to it, I am currently refactoring my code and once I have completed it I will perform some tests with beanstalk and I will inform you of the results.
Regards
Sehinde @ormrepo

**Comment by pentium10** [comment]
Notice: Undefined variable: tubes error has been handled in the latest release. Let me know if you still have the issue.

**Comment by phuclh** [comment]
I'm still getting this error. Followed the Laracasts tutorial. And I don't see any errors. Please help me.

<img width="1440" alt="screen shot 2016-01-27 at 01 43 05" src="https://cloud.githubusercontent.com/assets/6707194/12590815/596df262-c497-11e5-91cf-efc281327932.png">

<img width="1440" alt="screen shot 2016-01-27 at 01 43 42" src="https://cloud.githubusercontent.com/assets/6707194/12590825/6be25190-c497-11e5-97e9-2cca93ebff64.png">

**Comment by pentium10** [comment]
@phuclh make sure that you can connect to that address, as this means beanstalkd daemon is not started or you cannot connect to it

**Comment by phuclh** [comment]
@pentium10 Yes. I sure that I can connect to beanstalkd.dev

<img width="330" alt="screen shot 2016-01-27 at 02 30 39" src="https://cloud.githubusercontent.com/assets/6707194/12592215/11b124f6-c49e-11e5-8cd1-1deaad70e632.png">

<img width="466" alt="screen shot 2016-01-27 at 02 31 07" src="https://cloud.githubusercontent.com/assets/6707194/12592219/18a748e4-c49e-11e5-8a9c-21df22e44d3f.png">

**Comment by iaK** [comment]
Having the same problem as @phuclh . Any solution yet?

**Comment by andela-sakande** [comment]
I use valet, so I just make sure that both the console and the app are running on valet.
