### ISSUE TITLE
Q: Laravel + beanstalk_console

### ISSUE THREAD

**Issue by maxchirkov** [ptrofimov/beanstalk_console#101]
Hi there,

I have a general question, which I hope you could help me with. 

I'm trying to manage Laravel Job Queue via beanstalk_console, and everything seem to be great when it comes to monitoring, except for when I kick buried jobs. I'm burying jobs that actually fail in Laravel, which means - they can't be executed successfully. I bury them for the purpose of investigating the issue and then re-starting after the issue is fixed. When I kick a buried failed job from beanstalk_console - it looks like it gets processed and then deleted from the queue. The problem is, it's still a failing job, it's supposed to get buried again, but that doesn't happen. Any ideas why would it be happening?

**Comment by pentium10** [comment]
It's something in the code, that makes the job be deleted. So look closer.
I haven't heard about similar issues.

**Comment by maxchirkov** [comment]
Thanks for your response. Unfortunately I'm not sure where to look. I made my job handler to bury jobs, so it doesn't do anything beside simply burying each job that is being processed. After kicking a job - it disappears. I'll ask in Laravel forums as well. Thanks

**Comment by maxchirkov** [comment]
I figured it out - the issue was due to set tries limitation. When number of attempts reaches the limit, job gets automatically deleted. It wasn't obvious to me, but I got it through trial and error. Thanks!
