### ISSUE TITLE
Tubes show and disappear

### ISSUE THREAD

**Issue by tienkhoi** [ptrofimov/beanstalk_console#105]
I'm using beanstalk with laravel. Not sure why the second and third tube keeps flashing on and off. and they automatically reset the total job. is there anyway we can make those tubes stay permanently as the first tube does. Thank you

![image](https://cloud.githubusercontent.com/assets/7607653/9410276/6277edda-47ed-11e5-80bb-011d1fced01c.png)

**Comment by pentium10** [comment]
This is not from this extension.

Tubes stop to exists when no worker listens to it. So what you see here is that your workers stop listen then they rejoin. Check your code for this issue.

**Comment by jeff-h** [comment]
I know this is both off-topic for this project and quite old, but @tienkhoi did you get to the bottom of this problem? I've just fresh installed everything now in 2017 and still have the exact same issue you mention.

**Comment by pentium10** [comment]
if the tubes disappear it means they stop existing eg: there is no single job waiting, and there is not listener to it. Please note tubes are not persisted in beanstalkd protocol. So don't expect they stay there.

**Comment by jeff-h** [comment]
@pentium10 Thanks for your response — makes sense. However, when using this project in the context of Laravel, there's something going on (on the laravel side) which causes the jobs to disappear. I am hoping @tienkhoi might have found out how to get around it.
