### ISSUE TITLE
PHP7 not supported?

### ISSUE THREAD

**Issue by Jaspur** [ptrofimov/beanstalk_console#111]
See:
![schermafdruk 2015-09-24 09 48 15](https://cloud.githubusercontent.com/assets/4254854/10068039/76584e34-62a1-11e5-88f9-6bdcc60b72b0.png)
PHP 7.0.0RC3

**Comment by pentium10** [comment]
This is a local setup issue and not the projects, you need to give permissions to PHP to read/write the session folder.

**Comment by Jaspur** [comment]
@pentium10 that folder doesn't exists when you run on php7.

**Comment by pentium10** [comment]
In our project we don't reference that folder. It's a PHP internal session handling, so you need to fix your PHP.

**Comment by goldencut** [comment]
Sry to awake old thread but I'm kind of timid... :P 
Does BC work with PHP 7?

**Comment by pentium10** [comment]
@goldencut I had no time to test on PHP7. The code is simple maybe you are able to fix and create a Pull Request for PHP7 support. Interested?

**Comment by goldencut** [comment]
Probably not simple enough. Sry, that would take forever, and be ugly - I'm more of a sysadmin than dev... :/ Have you tried running it, any particular reasons it shouldn't run on 7?

**Comment by pentium10** [comment]
I didn't had time to run it, currently we use on 5.4
try creating a container for it using php 5.4, this way you can secure it. 

you can also add servers outside of the container to the interface, as it doesn't have to be on the same machine.

**Comment by Jaspur** [comment]
Nope, it's fucked on PHP7. Only working good on deprecated 5.4.

**Comment by relm** [comment]
I haven't had any issues running BC on PHP 7. Been using it for awhile.

**Comment by goldencut** [comment]
Hmm... relm, did you have to modify any of BC files to get it to work with php7?

**Comment by relm** [comment]
Nope. I haven't tried the latest version of BC though, I'm running an older version (1.7.4)

**Comment by goldencut** [comment]
BC 1.7.6 runs on nginx 1.6.2 and php7(-fpm).

**Comment by mkopinsky** [comment]
Working fine for me on PHP 7.1. @Jaspur I know this is old, but if you can share any error messages you get when running this on PHP7 I can look into it.

**Comment by pentium10** [comment]
fixed with release 1.7.9
