### ISSUE TITLE
Missing -i flag on last sed invocation on `docker/run.sh`

### ISSUE THREAD

**Issue by hugochinchilla** [ptrofimov/beanstalk_console#112]
Default beanstalk server is not configured when using links because there is a missing `-i` flag to sed in line 29 on `docker/run.sh`.

**Comment by pentium10** [comment]
Fixed with 5562e8f8dd1ab7cddaa234d81ec4576b2630b370

**Comment by hugochinchilla** [comment]
Thanks!
