### ISSUE TITLE
Headers already send

### ISSUE THREAD

**Issue by Donny5300** [ptrofimov/beanstalk_console#116]
After deleting a record from the tube this error shows up. Clicking on "Click to open" doesn't do anything.

Unserialize got a fatal error, please include the necessary files, or deactivate unserialization from Settings (click to open)

Warning: Cannot modify header information - headers already sent by (output started at /home/beanconsole/lib/BeanstalkInterface.class.php:255) in /home/beanconsole/lib/include.php on line 414

**Comment by s22su** [comment]
You need to go to settings and disable "before display: unserialize()" setting.
