### ISSUE TITLE
Error on tube view

### ISSUE THREAD

**Issue by luchaninov** [ptrofimov/beanstalk_console#123]
When you try to view the tube there is a warning:

    Warning: Invalid argument supplied for foreach() in /var/www/lib/tpl/currentTubeJobsShowcase.php on line 2

Several browser refreshes help - there is some change that this warning does not appear. But this is really annoying.

You could check if array is ok (not null for example) before using it in `foreach`:

    <?php if ($peek) foreach ($peek as $state => $job): ?>

**Comment by pentium10** [comment]
fixed by the latest commit, please test
