### ISSUE TITLE
how to set up autoloading for serialized classes in jobs?

### ISSUE THREAD

**Issue by jdmcalee** [ptrofimov/beanstalk_console#124]
I'm using serialized PHP objects as job data, which works fine if I edit index.php to include the composer autoloader from the project containing those classes. Is there a better way to include arbitrary paths into the autoloading for beanstalk_console so it can display these things properly?

**Comment by pentium10** [comment]
There is no standard defined or components to do this way. If you have ideas how to improve it, let us know.

**Comment by jdmcalee** [comment]
Alright, thanks. I'll poke around.
