### ISSUE TITLE
The server is unavailable

### ISSUE THREAD

**Issue by micmicsuarez** [ptrofimov/beanstalk_console#134]
I got this error when I added a new server in `beanstalk-console` app that runs in CentOS environment.
```
The server is unavailable
```

`Beanstalkd` is perfectly running in my server. 

Thanks,
Michael

**Comment by pentium10** [comment]
This error message is printed when cannot be established a connection, check your host/firewall/ports try from telnet also.

**Comment by micmicsuarez** [comment]
I can telnet the server where the beanstalk service is running.
```
[root@sniperhimo-server ~]# telnet 10.X.X.X 11300
Trying X.X.X.X...
Connected to 10.X.X.X.
Escape character is '^]'.
```

**Comment by pentium10** [comment]
try printing the exception from this line: https://github.com/ptrofimov/beanstalk_console/blob/39890344e499f75e1541b8939d46e33e161bbb32/lib/include.php#L354

**Comment by micmicsuarez** [comment]
thanks @pentium10.

**Comment by micmicsuarez** [comment]
hi @pentium10, I printed the exception. It seems that there is a problem in the connection. 

```
 exception 'Pheanstalk_Exception_ConnectionException' with message 'Socket error 13: Permission denied' in /var/www/beanstalk-console/lib/Pheanstalk/Socket/NativeSocket.php:36 Stack trace: #0 /var/www/beanstalk-console/lib/Pheanstalk/Connection.php(138): Pheanstalk_Socket_NativeSocket->__construct('10.129.2.74', '11300', 2) #1 /var/www/beanstalk-console/lib/Pheanstalk/Connection.php(70): Pheanstalk_Connection->_getSocket() #2 /var/www/beanstalk-console/lib/Pheanstalk.php(376): Pheanstalk_Connection->dispatchCommand(Object(Pheanstalk_Command_ListTubesCommand)) #3 /var/www/beanstalk-console/lib/Pheanstalk.php(114): Pheanstalk->_dispatch(Object(Pheanstalk_Command_ListTubesCommand)) #4 /var/www/beanstalk-console/lib/BeanstalkInterface.class.php(22): Pheanstalk->listTubes() #5 /var/www/beanstalk-console/lib/include.php(339): BeanstalkInterface->getTubes() #6 /var/www/beanstalk-console/lib/include.php(42): Console->_main() #7 /var/www/beanstalk-console/public/index.php(43): Console->__construct() #8 {main}
```

**Comment by pentium10** [comment]
it's from your system, something it's not setup correctly, hard to tell
but it's not coming from library

**Comment by micmicsuarez** [comment]
Is the SELinux preventing the http user accessing the beanstalkd port?

**Comment by micmicsuarez** [comment]
@pentium10, I agree with you. Will fix it and notify you the update. Thanks

**Comment by pentium10** [comment]
I don't know if SELinux or something else, I am not experienced on shell.

**Comment by micmicsuarez** [comment]
@pentium10, I fixed it by executing this command in the server where the `beanstalk-console` is running.

```
sudo semanage port -a -t http_port_t -p tcp 11300
```

Thanks for your help @pentium10 :)
