### ISSUE TITLE
Unserialize or Base64decode got a fatal error

### ISSUE THREAD

**Issue by timramseyjr** [ptrofimov/beanstalk_console#135]
What does 'Unserialize or Base64decode got a fatal error, please include the necessary files, or deactivate unserialization from Settings' mean.  I checked the error logs and didn't see a specific error.

**Comment by pentium10** [comment]
by default Base64Decode is active, but if you don't need that prettyfier you can turn it off in the menu

**Comment by pentium10** [comment]
please confirm you understood

**Comment by timramseyjr** [comment]
From what I gather it is a message about the formatting of serialized data in the queue?  It sounded like with 'please include the necessary files' that there was some extension that needed activating or something.

**Comment by pentium10** [comment]
yep, this is for that situation, when someone has a custom project, with custom classes in their message and in order to properly display the job snippet the library needs those classes as well
