### ISSUE TITLE
Moving a buried job back to a tube being watched by multiple workers causes same job to be reserved multiple times?

### ISSUE THREAD

**Issue by georaldc** [ptrofimov/beanstalk_console#140]
Not exactly sure at the moment if there's an issue with my code but I only noticed this behavior with beanstalk console. If I have a buried job and want to put it back into my queue using the "Move all buried to" option, all my workers seem to pick up the same job at the exact same time (interestingly, all with a different job ID) and try to process it. While they all would end up being buried again immediately (this is expected behavior), I only see one buried job on the console dashboard, despite my logs showing all those different job IDs being handled by my workers simultaneously (all with the same data since they all are just the same job) being buried at the same time. Basically the latest job ID that gets buried only shows up. I use pheanstalk to interact with my beanstalkd server and my worker code is pretty straightforward:

```
$pheanstalk = new \Pheanstalk\Pheanstalk(ip, port);
$pheanstalk->watch('a specific tube');
while ($job = $pheanstalk->reserve()) {
    // Immediately bury a job to prevent it from being put back into the queue if something bad happens
    $pheanstalk->bury($job);
    
    // Process job here. Delete job when done, or leave it buried if an exceptional error occurs.
}
```

I then have supervisord handle spinning up multiple instances that run that block of code. Other parts of my code that deal with pushing stuff to the queue work just fine and are handled one-to-one by whichever worker is able to reserve a job first. It's only when I use the beanstalk console to bring buried jobs back do I see duplicate processing.

**Comment by georaldc** [comment]
So I realized that this problem still occurs even with just a single worker watching a tube (it just gets compounded with multiple workers). Looking at the code, I believe this occurs because of what's happening here:

https://github.com/ptrofimov/beanstalk_console/blob/1.7.7/lib/include.php#L765

If I bury a job immediately like in my sample code, it's possible for the do/while loop here to pick it up again ($job = $this->interface->_client->useTube($tube)->peekBuried();) before it is able to exit out via throwing a Pheanstalk_Exception_ServerException exception from not finding any jobs. That explains why I only see 1 buried job, despite it being executed and buried more than once. I'm guessing this a race condition type of problem?

**Comment by pentium10** [comment]
How I see is:

- you have a worker listening for new jobs (and as you say bury them immediately)
- you click move ALL from Bury to Ready
- loop clicks in to peek all Bury
- identifies a buried, creates a copy puts to ready
-      workers takes the new copy and buries 
- loop deletes the buried and loops again (since there is a new bury already in place as the worker did created meanwhile the bury it keeps doing this)

I think you should pause the tube and then click the buttons. Otherwise because your workers are too fast, the console cannot do it's thing correctly.

**Comment by georaldc** [comment]
That basically sums it up. I guess there are ways around it (like your suggestion of pausing) but that can be quite a hassle. If this is expected behavior, then this issue can be closed.

**Comment by pentium10** [comment]
we cannot build around your logic, actually your logic of fast bury makes you this behaivior
