### ISSUE TITLE
502  Bad Gateway error

### ISSUE THREAD

**Issue by zhoujun165** [ptrofimov/beanstalk_console#145]
lunch from public directory but 502  Bad Gateway error

**Comment by pentium10** [comment]
check your server logs it should be a clear message what cannot load
this is a bad configuration issue you need to find out, it's not an error on the project

**Comment by zhoujun165** [comment]
it is ok when I delete one line of code 'Pheanstalk_ClassLoader::register(dirname(__FILE__));' at lib/include.php
