### ISSUE TITLE
composer/installers support

### ISSUE THREAD

**Issue by archon810** [ptrofimov/beanstalk_console#154]
Hi,

Please add support for https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md so that we can incorporate beanstalk_console and specify a custom install path during installation.

Thanks.

**Comment by mkopinsky** [comment]
beanstalk_console isn't a package for a framework, so I'm not sure what you're asking. You can install beanstalk_console to a custom install path using the {{composer create-project}} syntax shown on the readme.

**Comment by archon810** [comment]
Ideally, what I'd like to do is be able to update beanstalk_console just like other dependencies, using composer.

Now that I thought about it, I realized the config file may get overwritten that way, along with storage.json and maybe the .htaccess I'd add, so I think more tweaks would be needed to make this work with composer.

Any suggestions? For now, I am using beanstalk_console as part of a checked in code in our repo, and updates are done manually using a diff tool.

**Comment by mkopinsky** [comment]
This is a bit "old school", but the way I'm doing it: `composer create-project` basically just does a `git clone`. To update: `git pull`.

**Comment by archon810** [comment]
If this could be just added to composer.json, it'd resolve this issue:

```
"require": {
        "composer/installers": "~1.0"
    }
```

Then in our own project's composer.json:

```
        {
            "type": "vcs",
            "url": "git@github.com:ptrofimov/beanstalk_console.git"
        },
```

Then:
```
"ptrofimov/beanstalk_console": "1.7.11",
```

Then:
```
 "extra": {
        "installer-paths": {
            "public/beanstalk_console": [
                "ptrofimov/beanstalk_console"
            ]
        }
    },
```

This way, it'd get installed into public/ instead of vendor/

**Comment by pentium10** [comment]
I finally committed the one liner "composer/installers": "~1.0"

**Comment by archon810** [comment]
Hmm, it's still installing into the `vendor` dir in my tests. Were you able to get it to work?
