### ISSUE TITLE
Setting to enable auto-refresh by default

### ISSUE THREAD

**Issue by archon810** [ptrofimov/beanstalk_console#156]
I love the auto-refresh button, and I wish it was enabled by default every time you load the console, but it gets turned off every time.

Please consider adding a setting to have it on by default.

**Comment by archon810** [comment]
@mkopinsky Thoughts on this?

**Comment by mkopinsky** [comment]
I'm not the "official" maintainer of this, so any contributions I make are simply to scratch my own itch. I haven't been using beanstalk_console much since the set of pull requests I opened a while back, but if I start using it some more I'll consider opening a PR for that.

**Comment by archon810** [comment]
Ah, apologies. cc'ing @ptrofimov

**Comment by shaunpud** [comment]
#164

**Comment by archon810** [comment]
@shaunpud @pentium10 I just rolled this out, but I'm seeing a bug. Can you please reopen the ticket?

The bug is: the setting doesn't work on the All servers page. It does seem to work when I go to individual servers, however.

**Comment by archon810** [comment]
@shaunpud @pentium10 Please reopen to tweak the final fix.

**Comment by archon810** [comment]
Thank you.

**Comment by archon810** [comment]
Any updates please?

**Comment by archon810** [comment]
Unless I misunderstood the release notes, I think https://github.com/ptrofimov/beanstalk_console/releases/tag/1.7.11 signals that it fixes this issue, but after testing it, it still doesn't work.

**Comment by pentium10** [comment]
@archon810 could you tell more details about what's not working?
I tested again and it works for us also on FF and Chrome. did you cleared the cache?

**Comment by archon810** [comment]
You know, it ended up being the browser cache after all. Thanks!
