### ISSUE TITLE
What's the logic about search?

### ISSUE THREAD

**Issue by mmenozzi** [ptrofimov/beanstalk_console#161]
Hi,
in the `findJobsByState ` you search for all jobs in a given state by getting jobs one by one from the first returned by the related peek command to a `$lastId` calculated as follows:

https://github.com/ptrofimov/beanstalk_console/blob/9d27c122e8836c233108812637b925a9ae2b5363/lib/include.php#L724

This appears to be wrong because the last job ID in that tube could be much more greater than the first ID plus the count of the jobs in that state. Take this example about buried jobs in a tube:

First buried job: ID=1
Then on the same tube we put, reserve and delete jobs until job ID=100
Than we bury another job ID=101

In such situation we have 2 buried jobs and the `$lastId` will be `1+2=3` so the console will search through job 1 and 2 and only job 1 will be returned because the job 2 is a deleted job.

**Comment by pentium10** [comment]
yep that  needs to be updated
I am travelling for 2 weeks, will see when I have time to do a pull request

**Comment by mmenozzi** [comment]
If you want I can do it but the problem is: how?
How can we know what's the maximum ID to search for? The stats-tube command doesn't have this information. Any idea?

**Comment by pentium10** [comment]
as far I know there is no way to obtain the last job id, as the queue doesn't expose it.
we need to loop all jobs until we reach one limit
- eg the maximum number of jobs to return eg: 20 results
- or we have fetched total number of jobs that exists on the tube itself

this last one could also mean that if some other tube has 1 million message, they will be peaked.
we could also introduce another two factors
- total system jobs to check eg: 10 000
- or total number of seconds allowed to fetch for jobs eg: 30 seconds

what do you think?

**Comment by mmenozzi** [comment]
Yes I agree.
There is no elegant way to it because the beanstalkd tube is not "inspectable" by design. I'll try to provide a PR for this.

**Comment by mmenozzi** [comment]
@pentium10 look at the #162, what do you think?

**Comment by pentium10** [comment]
can we optimize a bit- stop searching at max 30 jobs, I see you already have $added you just need to stop after 30 results


in my current setup I have burry jobs since last year, those job ID is extremely low compared to current numberI am wondering if not's a waste to loop all possible job ID. 

    On Tuesday, March 6, 2018, 10:03:42 AM GMT+2, Manuele Menozzi <notifications@github.com> wrote:  
 
 
@pentium10 look at the #162, what do you think?

**Comment by mmenozzi** [comment]
It was already limited when I started to work on this. There was two kind of limits:

- It stops when it find 25 jobs
- Or it stops after 25 seconds

So if you have to many jobs it lasts for maximum 25 seconds.
