### ISSUE TITLE
Who to contact for security issues

### ISSUE THREAD

**Issue by JamieSlome** [ptrofimov/beanstalk_console#180]
Hey there!

I belong to an open source security research community, and a member (@nav-prak) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by pentium10** [comment]
use my username to G mail to send email regarding this repo

**Comment by JamieSlome** [comment]
@pentium10 - we can currently only give report access to @ptrofimov as it is a user-based repository, instead of an organization. Is @ptrofimov still actively contributing?

For reference, the report can be found here:

https://huntr.dev/bounties/9af1c35e-3f74-4c93-a241-e8be01335ec7/

**Comment by pentium10** [comment]
He is not active at all. In the last 5 years I've committed all the updates, check out the recent commits.

**Comment by JamieSlome** [comment]
Understood @pentium10 - we can get a magic URL sent over to you so that you can view the report without having to sign up. Just to confirm the contact e-mail should be:

pentium10@gmail.com

**Comment by pentium10** [comment]
yes

**Comment by JamieSlome** [comment]
@pentium10 - you should have just received an e-mail from us, cheers! 🎉

**Comment by pentium10** [comment]
received it

**Comment by JamieSlome** [comment]
@pentium10 - great 👍

**Comment by pentium10** [comment]
this has been addressed by #181
