### ISSUE TITLE
Remove the composer/installers dependency

### ISSUE THREAD

**Issue by SamMousa** [ptrofimov/beanstalk_console#191]
The installers package is meant for libraries that are imported into other applications.
The `type` in `composer.json` however specifies this is a **project**.
The installers package does nothing for such a type.

**Comment by pentium10** [comment]
So just to double confirm, 

should we remove `type: project` or should we remove `composer/installers` ?

**Comment by SamMousa** [comment]
Remove `composer/installers`

**Comment by pentium10** [comment]
fixed in 1.7.19
