### ISSUE TITLE
Unable to find image 'beanstalk_console:latest'

### ISSUE THREAD

**Issue by vkatochka** [ptrofimov/beanstalk_console#193]
Hello

Can you provide a link to the official docker image of "beanstalk console"?

trying to run:
> docker run -d -p "80:80" --name beanstalk_console beanstalk_console

got the error:
~~~
Unable to find image 'beanstalk_console:latest' locally
docker: Error response from daemon: pull access denied for beanstalk_console, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
~~~

Same thing with `docker login`. 
Can give any advice?

**Comment by pentium10** [comment]
This repo doesn't have a central docker image.
Before `run` command you need to build it.
