### ISSUE TITLE
Feature froze project for PHP 5.2 and open to accept pull request with namespacing.

### ISSUE THREAD

**Issue by pentium10** [ptrofimov/beanstalk_console#56]
Related tickets:
https://github.com/ptrofimov/beanstalk_console/pull/48
https://github.com/ptrofimov/beanstalk_console/pull/55

**Comment by needcaffeine** [comment]
Ah crap, I just realized that you're waiting on a commit from me.

**Comment by pentium10** [comment]
fixed with #90
