### ISSUE TITLE
Laravel / pheanstalk / Beanstalkd Error : Undefined Variable in tubes

### ISSUE THREAD

**Issue by ormrepo** [ptrofimov/beanstalk_console#79]
I keep on coming across this error and I am unable to add a server to the console screen The error occurs when I run php -S localhost:7654 -t public.

PHP Notice:  Undefined variable: tubes in /Users/myfilename/Code/beanstalk_console/lib/tpl/main.php on line 90

Do you have any idea what the cause it I have tried uninstalling and reinstalling many times but this hasn't worked. Beanstalk Queues are OK I can add to the queue and run php artisan queue:work no problem

**Comment by pentium10** [comment]
Not sure what's happening can you provide a link to a public area where I can check. Maybe some config is off on your end.

**Comment by yameste** [comment]
Hi

Are you asking me to upload my code to a public area ? or would you like to remote in to my machine to have a look ?

By the way this is happening on my local machine in its own environment, this hasn’t occurred on my hosted site. I will be testing the same config on my external site tomorrow….

Sehinde

**Comment by needcaffeine** [comment]
It's very likely that the actual issue here is that the code is using an uninitialized variable. Newer versions of PHP will generate that notice. You can turn off error_reporting for this app and get past this error.

**Comment by pentium10** [comment]
@yameste so if this is coming from error_reporting than this is not an error, it's just a notice. Which you can deactivate using error_reporting. Let me know about your progress.

**Comment by yameste** [comment]
Hi there

I have checked the php.ini file and error reporting is set to

error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT

display_errors = Off

display_startup_errors = Off

log_errors = On

track_errors = Off


Within Laravel this is set to use the production environment, when you mentioned deactivate error reporting do you mean set this value to null ?

Regards
yameste

**Comment by yameste** [comment]
BTW I am using

php -v 

HP 5.5.19-1+deb.sury.org~precise+1 (cli) (built: Nov 19 2014 19:32:57)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

**Comment by pentium10** [comment]
You need to remove also notice from the error_reporting

something like
```
error_reporting = E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT

also verify what's Laravel is using for production, you need to have & ~E_DEPRECATED & ~E_STRICT

**Comment by yameste** [comment]
I can confirm that I have removed the reference to E_NOTICE  within the php.ini file and can confirm that Laravel is using ~E_DEPRECATED & ~E_STRICT (through the php.ini file).
The laravel environment variable is set to production (localhost).

The same error in the tubes still persists after vagrant reload, I am accessing the beanstalk console using php -S localhost:7654 -t public within the beanstalk_console directory on my mac.

**Comment by pentium10** [comment]
@yameste You do not need to remove. You need to add E_NOTICE there, to be ignored.

In Laravel you need to add to global.php 

```
error_reporting(E_ALL & ~E_NOTICE & ~E_DEPRECATED & ~E_STRICT)

**Comment by yameste** [comment]
Hi
I have added the E_NOTICE variable in the php file and the global.php in my laravel app and it still comes up with the same error.

Is the beanstalk console designed to be installed on the same server or does it have to be on another server ?
Can the console be installed on local machines for testing purposes ?
Thanks
yameste

**Comment by pentium10** [comment]
IF you added the E_NOTICE correctly with the ignore flags it should not come up.
Add the same line to the config file under this project, as I have a feeling this project is installed outside of Laravel, and that confused me.

Beanstalk console can be installed on the same server, and can be installed on local machines.

**Comment by yameste** [comment]
Hi

OK I have amended the error_reporting section and I have added E_NOTICE within there. I have rebooted the vagrant instance and I started up the beanstalk console before adding it in the add server section under localhost:7654. And to clarify I have already amended the global.php within laravel to reflect the changes you specified. Unfortunately I am still receiving the same error in the browser localhostL7654.

Please see attached screenshots for confirmation
Thanks
yameste

**Comment by pentium10** [comment]
I think you are still using this outside of Laravel and you got messed in your configuration files.

**Comment by ormrepo** [comment]
I wasn’t using this outside of Laravel I was using Laravel 4.
I have since recreated this on vagrant using the same settings.
Once I have got my heard round Laravel 5 I will test this on Laravel 5 and report the results.

**Comment by pentium10** [comment]
When you have a new case, open a new issue. I am closing this now as it's not reproducible.
