### ISSUE TITLE
Hide console from other users ?

### ISSUE THREAD

**Issue by andregeges** [ptrofimov/beanstalk_console#80]
Hi, now my console online in my domain, but how to hidden this from other user ?

**Comment by pentium10** [comment]
You can password protect a directory using basic authentication

for Apache: https://wiki.apache.org/httpd/PasswordBasicAuth
for Nginx: https://www.digitalocean.com/community/tutorials/how-to-set-up-http-authentication-with-nginx-on-ubuntu-12-10

**Comment by yameste** [comment]
Hello
i dont understand your response
You wrote "Hi, now my console online in my domain, but how to hidden this from other user ?”

This is not my issue,  after installing the console in a laravel app the console is not there.

Are you saying this is an issue to do with Nginx or Apache ?
Please clarify ?

Regards
Yameste

**Comment by pentium10** [comment]
@yameste you have your issue elsewhere, not on this ticket.
On this ticket I was replying to @andregeges

**Comment by yameste** [comment]
OK
