### ISSUE TITLE
Docker image available

### ISSUE THREAD

**Issue by schickling** [ptrofimov/beanstalk_console#81]
Just wanted to let you know, that I've built a docker image for that. Should be even simpler to setup than vagrant: https://github.com/schickling/dockerfiles/tree/master/beanstalkd-console

Can be used like this:

```sh
$ docker run -d -p 11300:11300 --name beanstalkd schickling/beanstalkd
$ docker run -d -p 2080:2080 --link beanstalkd:beanstalkd schickling/beanstalkd-console
```

**Comment by yameste** [comment]
OK great I will check this out in the upcoming week
Thanks

**Comment by pentium10** [comment]
Docker support has been added.
