### ISSUE TITLE
Undefined variable: tubes

### ISSUE THREAD

**Issue by anil2050kumar** [ptrofimov/beanstalk_console#85]
Undefined variable: tubes in [..]/beanstalk_console/lib/tpl/main.php

Please can anyone help me

**Comment by pentium10** [comment]
Your PHP error_reporting is set to display notice messages. You need to change that.

**Comment by anil2050kumar** [comment]
Yes i have changed that error_reporting(0)

Now i won't see the error console, but shows "The server is unavailable" at http://localhost:7654/index.php?server=expone:11300

**Comment by pentium10** [comment]
This means the Beanstalkd server is not running or not accessible. Check your firewall maybe the port is blocked. Or you miss typed your host name.

**Comment by anil2050kumar** [comment]
Thank you for quick response

Host name is correct
Beanstalkd server is runner 
Port is also opened

Thank you

![screenshot from 2015-04-12 14 52 46](https://cloud.githubusercontent.com/assets/2909975/7105086/b3af4868-e124-11e4-8723-332934b70197.png)
![screenshot from 2015-04-12 14 57 40](https://cloud.githubusercontent.com/assets/2909975/7105087/b3b7f206-e124-11e4-83cd-4136a07cff1e.png)
![screenshot from 2015-04-12 14 58 42](https://cloud.githubusercontent.com/assets/2909975/7105088/b3bbfbbc-e124-11e4-82a2-b6fc89420007.png)

**Comment by anil2050kumar** [comment]
Thank you
I resolved it, Problem was in hosts file

**Comment by ormrepo** [comment]
What was wrong with the hosts file?
