### ISSUE TITLE
Error: "No input file specified"

### ISSUE THREAD

**Issue by unwarysheep** [ptrofimov/beanstalk_console#87]
Having followed the instructions to install this monitor on a fresh Homestead install I am navigating to the public folder as per instructions in a web browser but I'm encountering and error 
```
No input file specified
```
Which has thrown me somewhat because there are no obvious configuration options for an input file. Can someone help me on this? Thanks

**Comment by pentium10** [comment]
This message is being printed by your Nginx (or Apache) server, that cannot locate the configured directory index file. It might be a configuration error in your server config file, or you are trying to access a folder without a primary index file. Please note our project needs to be launched with /public/index.php
